sudo: false
language: node_js
branches:
  only:
  - develop
node_js:
- 14.1.0
script: npm run build
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
  - CXX=g++-4.8
  - secure: CkOeD5HALgiNQ/hk5RU2xrc74Ahturyi7QKEetwhVOuMZ+ts0lp9aqJvCXzNZOVuFF/+/Xw29dK+/U9C7hz+iHG+VyUQbveN02ZM8bUHFqbH4RM+jyDSrr/cOSNib2eIh7Lr7KVqyIDbTaPX7KRkITsDRi9Fh5HCGSykIP1tM6Y+gmo0SSXaAMQuHymj09mpTY0J7FQ2AhDoITwlJ5G+ZSjKl5kwx7UQqM2mvwfMeOaMsNtSBuvRBGerawTy/7ivKHKFs3WVf1N3Wbhn/7k2h+rxYVhg9im4npcjErp3RTtnWQej3t8TZcZqVJhPKybiK7V0gh04X1ICNLuKA0TPY64eLI5tDgomWJRwebQN+CQfiuSU+GMI8rri5w1x5YWww7w9pVO2YOk7T81Ulp6EmrXaiwPSCZ+Ybz2LI4D1/Fk2cm+4OCP22NtCjST1nN2GJOgpAnEq9wPNjDU6qb4NRy1bNX5W4t5ruY8eAasR5PAFZg2GtIKXXPW80vRnZHbPbiZwuObvTBFrMM/KSrJL7AOS6bV40kq/tPs1bdVlW3t4As8pVKirWqAaGS4Ev8NwhWFtMFAS1vmtK2UQSfhp3vy75dztKRbWWiBh7HZpBvbbI2yV+NvbyRfz1tehKJe+aQzLuIJtg2NYh7Er0VLLc+Lpy2Pi2eBjJv2tsEkQ0cE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
