sudo: false
language: node_js
branches:
  only:
  - develop
node_js:
- 14.1.0
script: npm run build
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
  - CXX=g++-4.8
  - secure: oeQArbG9nzQR8I7+jxby8x1gKyvQVOSYblqcuID7fN/XJKM5q1q9qXIkDL3cK+bjP/S3IIDAKTjtY9M6wMnO/cOJnt1mTPF+s0uE9ndmdjTo6MR6zLsQ5pmTnzyv35BCDrYKPa3JTPkdmDIfPCcZ/MPStr+KQjLeZhyJLJGZW6CJCpyzZp7B5+16QpMSKP44SDGCLeW6jZD+VG12LDw1j398mHVKyB/OW+vufhU/z/bUmpKsSaV90ZSbOzycQBJACWD+Qe/itiO9OtbliagQlVhyJpJJ8QqoAm06hvTLOnJmgsOioAlhgFPoaLkSPLYwnpbimIldw/I/3cAcaQYpIe6ia8Q8nhb93667MHmJnsHv9RN38PPmr4Ac/xqOzdX0MHJvQiEuOPIpvaaeFy2GtDj8cnt9EbOQTLMFD55nvW2tMSltOrDk4WsgNqoDXg4cn9hqgLy7QOoN30MhA7vrzf0h33uA5XJ37FRQI75dkAWFuD3R6qkABvbsErwamWFjTzqaIwtO8+XY3bYumtt3p9JisfM+fa8pam9SSos0r7q9c9NY7CE2StBRcghaRQJCb8KtRodSLPjU79CdplbMbw6wCXaswnZM7YTdwrpXodTf4TrURKyJyIauddQjymX/3qDeBqXOWpPStzsRLK1/V6L7rIgg5H7OsF/9kzfGekE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
