sudo: false
language: node_js
branches:
  only:
  - develop
node_js:
- 5.6.0
script: npm run build:prod
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
  - CXX=g++-4.8
  - secure: vkoKjoLMw14Q8nUQfN1Yo9sxdbSmZMhjhtt+C5iAcV2FaoWxdVRAyEnF6wGtIxqKB8QzOfG87uQiTYOh5tVVFbckoC0dOgq4oN6RjROcT11NW26JyaKpeJ/ELZ5vrtPhAziulyV0egU3l/wD/bLHT2RibdbBhnOK6SdI+oZyrMOYuQ5WOGdV9h+gtoqjUTjkURXstUcVTqTosgkPzzIttWrw0TTuRPPOhU+Lu4NAF5wx8+w0eWbZ4NkAmgl7ePdHFvIspoRF3+bF9LzhI2Vi7VAkIuJKMBgqjQHFajbrxgMi8GAHyyhg9O+pv5bfQdPIhVbZIURsGgDwx0F2H2viov8eSAW93baAaldq8DyhwJrcw2KQeq/Dkk15N1/Up+UCv89m68d92Cqo4RZLxcWZciNRBGe//CUf1VnqBJA85kyWcqOVpX76TRqtherM3hReGk/yojY2g/YDhb2tOxRSPZIQansnGC7vx5+Uju5UkaAUviq0AG7q2K/jOPzwHtTj8OAQxi/o9W/CO2aAEW6w6egj1WML2PoJWeDPGS3o0yxorAxaFSndDPhuqQe2KZEpfVOab+njM473xfF3QauoRvr1a0MjG8VEXQlMY9JPYgw62Rcly73U3ljRwowFnmFkwbQZTboH6uTUHt1b+PnlBntWuGCEYpQpKgvgQv4qKkc=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
