sudo: false
language: node_js
branches:
  only:
  - develop
node_js:
- 14.1.0
script: npm run build
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
  - CXX=g++-4.8
  - secure: XBxqM10Cvu4U6MgYFmckAAIvF0AKAB/mL6IZq8VBDZ8XRsuLL/V8WCNYe5F5jBoEb9UcCTvF4CIX3r1p0nYzD0qSJamwmWNfH6Euo2IGpTeukm+AZRc/WhPeUcnzA6PHHElJ5ZdvCjZJRz9hwlANH2GSwbJmocIUX0MQAtMb45IWx6AFlYMRL9tRGhg2udbz0ofBwwZnM9NObNYocv1ghNO7n1g90N+kvFM5ONv9peoqUot0fkAbvENAJnpvpSWNBdUwE0CQi6Av+NeHjSQYZfu89YTbBPjs5GUHwEtciNw+E7BOAPsCtHpEC7v9DTgs4oF9++UHId+GiclMu+pib/tt4o2x7V6G0/8P289lt5/WMvp30wJmD53Ddb9MC7rVMiHw87YoQ7VrdbV2tsrdrBKpONUb0NjAi37fAgRQRrXCDnL/8WOqifNF6F2y7nRKjafI09eMdp0+WQDEFAE4E70vnGn1qcBS8DWHlVqNeQD1JOnv0VyTuhFEiSPE8zFduwfvvfFH91UnTHIc4farm3ZvG28Gq40DFSA4WBOLYlpwgKWb1YO9GcLhs1AuY6wc3+MYIngW0P/NXJWwGnVZWUnUSDixj/F8xBQI0NDukJYWujQU0ivPJShbUi5Tdbt1rzMZWmt44wj7XinrIoOYimQFMvVx/1jK4+w3LQhdLaM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
