sudo: false
language: node_js
branches:
  only:
  - develop
node_js:
- 14.1.0
script: npm run build
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
  - CXX=g++-4.8
  - secure: GGb4hdTl++8fT7mbBLdccuXzBcbWPQAXJs5n6WqjIUja9+3+EAYUK5Onro/wKjEP0t31tG5XhTwAWZC21qnyCD1jLizSdQ/FgL9qxu7LXPc/MK1tfmAr1oZTmcz2Zs/ajuJgqhSJWFNz/ReRZZ5Tm+BRFmutxY/uJGSstMqK+9r5vJvEbYr+o9/u0LC8DPS3I/SiSvN7nfvlFvIOS8SKMr/7oyl4/LQLWLmR/2J3gx3PVk+Cbc8AC8/7t2SeXHQAMy/8ehLMNHmup/rB26xRzFrUSOHSLjTiMSAmLBQzIo1s1fSju1SkDhsJE/scUj9Qgw5KxCAsztTlLYPiJ2DoLfPfKZ5O6K/OumZsIUTmpkjsXvb8G8Y8o+lYPcO7+AcMmVu69qbSOXWmvetmyYz6tBp/zQTLGQDIfZgmeA/Yr5Yt3kE9V9BZa/kKceW3QEesrTvTTOXRZf0W/pro+h1WGCfH/CktqiXSwwBbqq3HGWvCld2fnSLdi+OoZLXh5BP8MfeIQbI1J2BX0Gr4eC4rp47i4vmh8RVLCeIrmJ+zBmDQxsOmCChzPpyeC9EVoekV84LoIwt9XO3myw+imWRwmkb95f++SDBdR1pAY5yczmiL7IhwQ60QB+nhfaxdf6QuCJ2XfN1N488mO2HWhsll87mzmd1ghG8laVOj0FXLMbw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
